# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
port: 3000
safe: true


# edit here to achieve your personal greatness
url: thalesbertaglia.com
baseurl: /
title: Thales Bertaglia
author: Thales Bertaglia
description: Personal blog and resume
avatar: rsz_foto.jpg
email: contact@thalesbertaglia.com
github: tfcbertaglia # username
#twitter: username
linkedin: thales-bertaglia
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: thalesbertaglia-com
google_analytics: UA-110962150-1

# needed for travis-ci build
exclude: [vendor]
